/**
 * Generate an .ics (iCalendar) file content from action plan items.
 * Users can import this into Google Calendar, Apple Calendar, Outlook, etc.
 */

interface CalendarEvent {
  title: string;
  description?: string;
  startDate: Date;
  endDate?: Date;
  allDay?: boolean;
}

const escapeICS = (text: string): string => {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
};

const formatDate = (date: Date, allDay: boolean): string => {
  if (allDay) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}${m}${d}`;
  }
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
};

const generateUID = (): string => {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}@rickyai`;
};

export const generateICS = (events: CalendarEvent[], calendarName = "RickyAI Action Plan"): string => {
  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//RickyAI//Action Plan//EN",
    `X-WR-CALNAME:${escapeICS(calendarName)}`,
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
  ];

  for (const event of events) {
    const allDay = event.allDay !== false;
    const endDate = event.endDate || new Date(event.startDate.getTime() + 86400000);

    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${generateUID()}`);
    lines.push(`DTSTAMP:${formatDate(new Date(), false)}`);

    if (allDay) {
      lines.push(`DTSTART;VALUE=DATE:${formatDate(event.startDate, true)}`);
      lines.push(`DTEND;VALUE=DATE:${formatDate(endDate, true)}`);
    } else {
      lines.push(`DTSTART:${formatDate(event.startDate, false)}`);
      lines.push(`DTEND:${formatDate(endDate, false)}`);
    }

    lines.push(`SUMMARY:${escapeICS(event.title)}`);
    if (event.description) {
      lines.push(`DESCRIPTION:${escapeICS(event.description)}`);
    }
    lines.push("END:VEVENT");
  }

  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
};

export const downloadICS = (icsContent: string, filename = "rickyai-action-plan.ics") => {
  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Convert action plan items (from AI strategy output) into calendar events.
 * Supports various formats from different steps.
 */
export const actionPlanToEvents = (
  actionPlan: any[],
  businessName?: string,
  startFrom?: Date
): CalendarEvent[] => {
  const baseDate = startFrom || new Date();
  const events: CalendarEvent[] = [];

  actionPlan.forEach((item, index) => {
    // Determine the date offset
    let dayOffset = index * 2; // default: every 2 days

    // Try to extract timeframe hints
    const timeframe = item.timeframe || item.timeline || item.when || "";
    if (timeframe.includes("this week")) {
      dayOffset = index;
    } else if (timeframe.includes("this month")) {
      dayOffset = 7 + index * 3;
    } else if (timeframe.includes("next quarter")) {
      dayOffset = 30 + index * 7;
    } else if (item.week) {
      dayOffset = (item.week - 1) * 7;
    } else if (item.day) {
      dayOffset = item.day - 1;
    }

    const eventDate = new Date(baseDate);
    eventDate.setDate(eventDate.getDate() + dayOffset);

    const title = item.action || item.title || item.topic || item.task || `Action ${index + 1}`;
    const parts: string[] = [];
    if (item.impact) parts.push(`Impact: ${item.impact}`);
    if (item.timeframe) parts.push(`Timeframe: ${item.timeframe}`);
    if (item.platform) parts.push(`Platform: ${item.platform}`);
    if (item.goal) parts.push(`Goal: ${item.goal}`);
    if (item.type) parts.push(`Type: ${item.type}`);
    if (item.description) parts.push(item.description);
    if (businessName) parts.push(`Business: ${businessName}`);
    parts.push("Generated by RickyAI");

    events.push({
      title: `📋 ${title}`,
      description: parts.join("\n"),
      startDate: eventDate,
      allDay: true,
    });
  });

  return events;
};

/**
 * Generate a Google Calendar URL for a single event (opens in browser).
 */
export const googleCalendarUrl = (event: CalendarEvent): string => {
  const start = formatDate(event.startDate, true);
  const end = event.endDate
    ? formatDate(event.endDate, true)
    : formatDate(new Date(event.startDate.getTime() + 86400000), true);

  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: event.title,
    dates: `${start}/${end}`,
    details: event.description || "",
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
};
